<a href="https://colab.research.google.com/github/rene-hiroki/gazoubunrui/blob/master/testprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 試行・実験

In [4]:
!pwd
%cd drive/My Drive/gazo2020/original_data

/content/drive/My Drive/gazo2020/original_data
[Errno 2] No such file or directory: 'drive/My Drive/gazo2020/original_data'
/content/drive/My Drive/gazo2020/original_data


In [5]:
import sys
# sys.path.append('/content/drive/My Drive/Colab/my_project/my_modules')
sys.path.append('/content/drive/My Drive/gazo2020/module')

In [7]:

import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000001.jpg
>> 計算結果↓
[[9.8598135e-01 1.3928427e-02 9.0238478e-05]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000002.jpg
>> 計算結果↓
[[9.9928015e-01 5.1677448e-04 2.0315521e-04]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000003.jpg
>> 計算結果↓
[[9.9937314e-01 6.2673591e-04 7.7371404e-08]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000004.jpg
>> 計算結果↓
[[9.9903905e-01 9.6081081e-04 7.4474748e-08]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000008.jpg
>> 計算結果↓
[[9.9772733e-01 2.2725323e-03 1.4338902e-07]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000009.jpg
>> 計算結果↓
[[9.9504179e-01 4.9570198e-03 1.2006786e-06]]
>> この画像は「kobe」です。

>> 入力したい画像ファイル(