<a href="https://colab.research.google.com/github/rene-hiroki/gazoubunrui/blob/master/testprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 試行・実験

In [1]:
%cd drive/My Drive/gazo2020/original_data
!pwd

/content/drive/My Drive/gazo2020/original_data
/content/drive/My Drive/gazo2020/original_data


In [2]:
import sys
# sys.path.append('/content/drive/My Drive/Colab/my_project/my_modules')
sys.path.append('/content/drive/My Drive/gazo2020/module')

In [3]:

import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000001.jpg
>> 計算結果↓
[[0.00403762 0.9124872  0.0834752 ]]
>> この画像は「westbrook」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000002.jpg
>> 計算結果↓
[[0.00143694 0.8791424  0.11942063]]
>> この画像は「westbrook」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000003.jpg
>> 計算結果↓
[[0.00723527 0.9905612  0.00220357]]
>> この画像は「westbrook」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000004.jpg
>> 計算結果↓
[[0.00248439 0.9520499  0.04546572]]
>> この画像は「westbrook」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000005.jpg
>> 計算結果↓
[[0.00916179 0.18073805 0.81010014]]
>> この画像は「curry」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazo2020/original_data/test/000006.jpg
>> 計算結果↓
[[0.00487031 0.9362047  0.05892505]]
>> この画像は「westbrook」です。

>> 入力したい画像ファイル(「END」で終了) ： 
>> そのファイルは存在しませ